og5.0.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -709,6 +709,7 @@ with_selinux
 krb_srvtab
 with_python
 with_openeuler_os
+with_openeuler_major
 enable_thread_safety
 INCLUDES
 TAS
@@ -751,6 +752,7 @@ enable_jemalloc_debug
 enable_privategauss
 enable_multiple_nodes
 enable_lite_mode
+enable_finance_mode
 enable_mot
 enable_memory_check
 enable_mysql_fdw
@@ -828,6 +830,7 @@ enable_nls
 with_pgport
 with_gs_version
 with_openeuler_os
+with_openeuler_major
 enable_shared
 enable_rpath
 enable_jemalloc
@@ -835,6 +838,7 @@ enable_jemalloc_debug
 enable_privategauss
 enable_multiple_nodes
 enable_lite_mode
+enable_finance_mode
 enable_mot
 enable_memory_check
 enable_mysql_fdw
@@ -2195,7 +2199,7 @@ PACKAGE_VERSION='9.2.4'
 # Postgres-XC 1.1devel is based on PostgreSQL 9.2.4
 PACKAGE_XC_VERSION='1.1'
 # openGauss is based on PostgreSQL 9.2.4 and it will be the Kernel of GaussDB database
-OPENGAUSS_VERSION='3.0.0'
+OPENGAUSS_VERSION='5.0.1'
 
 cat >>confdefs.h <<_ACEOF
 #define PG_VERSION "$PACKAGE_VERSION"
@@ -2672,8 +2676,13 @@ else
   commits=$(git log 2>/dev/null | grep "See in merge request" | wc -l)
   debug_str=""
   mrid=$(git log 2>/dev/null | grep "See merge request" | head -1 | awk -F! '{print $2}' | grep -o '[0-9]\+')
+  
+  if test "${enable_finance_mode}" = yes; then
+      product="${product}-finance"
+  fi
+
   if test "$enable_debug" = yes; then
-    debug_str="debug"
+      debug_str="debug"
   fi
 
   if test "$enable_ccache" = yes; then
@@ -3229,6 +3238,48 @@ _ACEOF
 
 fi
 
+#
+# --enable-finance-mode enables
+#
+
+# Check whether --enable-finance-mode was given.
+if test "${enable_finance_mode+set}" = set; then
+  enableval=$enable_finance_mode;
+  case $enableval in
+    yes)
+      if test "$enable_lite_nodes" = yes; then
+        { { $as_echo "$as_me:$LINENO: error: --enable-finance-mode option is not supported with --enable-lite-nodes option" >&5
+            $as_echo "$as_me: error: --enable-finance-mode option is not supported with --enable-lite-nodes option" >&2;}
+              { (exit 1); exit 1; }; }
+      fi
+      ;;
+    no)
+      :
+      ;;
+    *)
+      { { $as_echo "$as_me:$LINENO: error: no argument expected for --enable-finance-mode option" >&5
+$as_echo "$as_me: error: no argument expected for --enable-finance-mode option" >&2;}
+   { (exit 1); exit 1; }; }
+      ;;
+  esac
+
+else
+  enable_finance_mode=no
+
+fi
+
+if test "$enable_lite_nodes" = yes; then
+
+  enable_finance_mode=no
+fi
+
+if test "$enable_finance_mode" = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_FINANCE_MODE 1
+_ACEOF
+
+fi
 
 #
 # --with-openeuler-os enable
@@ -3272,6 +3323,9 @@ _ACEOF
 
 fi
 
+if [ "$(cat /etc/system-release)" == "openEuler release 22.03 LTS" ]; then
+    with_openeuler_major=yes
+fi
 
 #
 # --enable-coverage enables generation of code coverage metrics with gcov
@@ -3710,8 +3764,11 @@ case ${wal_segsize} in
  16) ;;
  32) ;;
  64) ;;
-  *) { { $as_echo "$as_me:$LINENO: error: Invalid WAL segment size. Allowed values are 1,2,4,8,16,32,64." >&5
-$as_echo "$as_me: error: Invalid WAL segment size. Allowed values are 1,2,4,8,16,32,64." >&2;}
+ 128) ;;
+ 256) ;;
+ 512) ;;
+  *) { { $as_echo "$as_me:$LINENO: error: Invalid WAL segment size. Allowed values are 1,2,4,8,16,32,64,128,256,512." >&5
+$as_echo "$as_me: error: Invalid WAL segment size. Allowed values are 1,2,4,8,16,32,64,128,256,512." >&2;}
    { (exit 1); exit 1; }; }
 esac
 { $as_echo "$as_me:$LINENO: result: ${wal_segsize}MB" >&5
@@ -3722,6 +3779,18 @@ cat >>confdefs.h <<_ACEOF
 #define XLOG_SEG_SIZE (${wal_segsize} * 1024 * 1024)
 _ACEOF
 
+# Set number of MAX_ALLOC_SEGNUM in extreme_rto
+if test "${wal_segsize}" -lt 256; then
+  MAX_ALLOC_SEGNUM=4
+elif test "${wal_segsize}" -ge 256 -a "${wal_segsize}" -lt 512; then
+  MAX_ALLOC_SEGNUM=2
+else
+  MAX_ALLOC_SEGNUM=1
+fi
+
+cat >>confdefs.h <<_ACEOF
+#define MAX_ALLOC_SEGNUM ${MAX_ALLOC_SEGNUM}
+_ACEOF
 
 #
 # C compiler
@@ -5890,8 +5959,7 @@ fi
 
 llvm_version_str='10.0.0'
 if [[ ! -z "${with_3rdpartydir}" ]] && [[ "$enable_lite_mode" != yes ]]; then
-    platstr=$(sh src/get_PlatForm_str.sh)
-    llvm_version_str=`${with_3rdpartydir}/dependency/${platstr}/llvm/comm/bin/llvm-config --version`
+    llvm_version_str=`${with_3rdpartydir}/kernel/dependency/llvm/comm/bin/llvm-config --version`
 fi
 llvm_major_version=$(echo $llvm_version_str | awk -F "." '{print $1}')
 llvm_minor_version=$(echo $llvm_version_str | awk -F "." '{print $2}')
@@ -6462,7 +6530,11 @@ fi
 # XML
 #
 
-
+if [[ "$enable_lite_mode" != yes ]]; then
+  with_libxml=yes
+else
+  with_libxml=no
+fi
 
 # Check whether --with-libxml was given.
 if test "${with_libxml+set}" = set; then
@@ -6490,10 +6562,11 @@ else
 
 fi
 
-
-
+xml2_cflag=${with_3rdpartydir}/kernel/dependency/libxml2/comm/include/libxml2
+xml2_lib=${with_3rdpartydir}/kernel/dependency/libxml2/comm/lib
+xml2_config=${with_3rdpartydir}/kernel/dependency/libxml2/comm/bin/xml2-config
 if test "$with_libxml" = yes ; then
-  for ac_prog in xml2-config
+  for ac_prog in ${xml2_config}
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -6522,7 +6595,7 @@ IFS=$as_save_IFS
 
 fi
 fi
-XML2_CONFIG=$ac_cv_prog_XML2_CONFIG
+XML2_CONFIG=$xml2_config
 if test -n "$XML2_CONFIG"; then
   { $as_echo "$as_me:$LINENO: result: $XML2_CONFIG" >&5
 $as_echo "$XML2_CONFIG" >&6; }
@@ -6538,12 +6611,12 @@ done
   if test -n "$XML2_CONFIG"; then
     for pgac_option in `$XML2_CONFIG --cflags`; do
       case $pgac_option in
-        -I*|-D*) CPPFLAGS="$CPPFLAGS $pgac_option";;
+        -I*|-D*) CPPFLAGS="$CPPFLAGS $pgac_option -I${xml2_cflag}";;
       esac
     done
     for pgac_option in `$XML2_CONFIG --libs`; do
       case $pgac_option in
-        -L*) LDFLAGS="$LDFLAGS $pgac_option";;
+        -L*) LDFLAGS="$LDFLAGS $pgac_option -L${xml2_lib}";;
       esac
     done
   fi
@@ -6622,18 +6695,17 @@ fi
 #
 with_jdk=''
 if [[ ! -z "${with_3rdpartydir}" ]] && [[ "$with_openeuler_os" != yes ]]; then
-    platstr=$(sh src/get_PlatForm_str.sh)
     cpuarch=$(uname -m)
     for d in "openjdk8" "huaweijdk8"; do
-        $as_echo "$as_me:$LINENO: checking for jdk in ${with_3rdpartydir}/platform/${d}/${cpuarch}" >&5
-        if [ ! -d "${with_3rdpartydir}/platform/${d}/${cpuarch}" ]; then
+        $as_echo "$as_me:$LINENO: checking for jdk in ${with_3rdpartydir}/kernel/platform/${d}/${cpuarch}" >&5
+        if [ ! -d "${with_3rdpartydir}/kernel/platform/${d}/${cpuarch}" ]; then
             $as_echo "$as_me:$LINENO: result: no" >&5
             continue
         fi
 
-        for d2 in $(ls "${with_3rdpartydir}/platform/${d}/${cpuarch}" | sort -r  2>/dev/null); do
-            if [ -f "${with_3rdpartydir}/platform/${d}/${cpuarch}/${d2}/jre/bin/java" ]; then
-                with_jdk="${with_3rdpartydir}/platform/${d}/${cpuarch}/${d2}"
+        for d2 in $(ls "${with_3rdpartydir}/kernel/platform/${d}/${cpuarch}" | sort -r  2>/dev/null); do
+            if [ -f "${with_3rdpartydir}/kernel/platform/${d}/${cpuarch}/${d2}/jre/bin/java" ]; then
+                with_jdk="${with_3rdpartydir}/kernel/platform/${d}/${cpuarch}/${d2}"
                 break;
             fi
         done
@@ -6643,15 +6715,15 @@ if [[ ! -z "${with_3rdpartydir}" ]] && [[ "$with_openeuler_os" != yes ]]; then
             break;
         fi
 
-        $as_echo "$as_me:$LINENO: checking for jdk in ${with_3rdpartydir}/platform/${platstr}/${d}" >&5
-        if [ ! -d "${with_3rdpartydir}/platform/${platstr}/${d}" ]; then
+        $as_echo "$as_me:$LINENO: checking for jdk in ${with_3rdpartydir}/kernel/platform/${d}" >&5
+        if [ ! -d "${with_3rdpartydir}/kernel/platform/${d}" ]; then
             $as_echo "$as_me:$LINENO: result: no" >&5
             continue
         fi
 
-        for d2 in $(ls "${with_3rdpartydir}/platform/${platstr}/${d}" | sort -r  2>/dev/null); do
-            if [ -f "${with_3rdpartydir}/platform/${platstr}/${d}/${d2}/jre/bin/java" ]; then
-                with_jdk="${with_3rdpartydir}/platform/${platstr}/${d}/${d2}"
+        for d2 in $(ls "${with_3rdpartydir}/kernel/platform/${d}" | sort -r  2>/dev/null); do
+            if [ -f "${with_3rdpartydir}/kernel/platform/${d}/${d2}/jre/bin/java" ]; then
+                with_jdk="${with_3rdpartydir}/kernel/platform/${d}/${d2}"
                 break;
             fi
         done
@@ -9828,7 +9900,7 @@ if test "${ac_cv_lib_xml2_xmlSaveToBuffer+set}" = set; then
   $as_echo_n "(cached) " >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lxml2  $LIBS"
+LIBS="-L${xml2_lib} -lxml2 -lm -ldl $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -13420,6 +13492,7 @@ done
 fi
 
 if test "$with_libxml" = yes ; then
+  CPPFLAGS="-I${xml2_cflag} $CPPFLAGS"
   if test "${ac_cv_header_libxml_parser_h+set}" = set; then
   { $as_echo "$as_me:$LINENO: checking for libxml/parser.h" >&5
 $as_echo_n "checking for libxml/parser.h... " >&6; }
@@ -18202,9 +18275,47 @@ fi
 
 # On PPC, check if assembler supports LWARX instruction's mutex hint bit
 case $host_cpu in
+  x86_64)
+    # On x86_64, check if we can compile a popcntq instruction
+    { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether assembler supports x86_64 popcntq" >&5
+$as_echo_n "checking whether assembler supports x86_64 popcntq... " >&6; }
+if ${pgac_cv_have_x86_64_popcntq+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+long long x = 1; long long r;
+	 __asm__ __volatile__ (" popcntq %1,%0\n" : "=q"(r) : "rm"(x));
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  pgac_cv_have_x86_64_popcntq=yes
+else
+  pgac_cv_have_x86_64_popcntq=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $pgac_cv_have_x86_64_popcntq" >&5
+$as_echo "$pgac_cv_have_x86_64_popcntq" >&6; }
+    if test x"$pgac_cv_have_x86_64_popcntq" = xyes ; then
+
+$as_echo "#define HAVE_X86_64_POPCNTQ 1" >>confdefs.h
+
+    fi
+  ;;
+  
   ppc*|powerpc*)
     { $as_echo "$as_me:$LINENO: checking whether assembler supports lwarx hint bit" >&5
 $as_echo_n "checking whether assembler supports lwarx hint bit... " >&6; }
+if ${pgac_cv_have_ppc_mutex_hint+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -18248,6 +18359,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
     { $as_echo "$as_me:$LINENO: result: $pgac_cv_have_ppc_mutex_hint" >&5
 $as_echo "$pgac_cv_have_ppc_mutex_hint" >&6; }
     if test x"$pgac_cv_have_ppc_mutex_hint" = xyes ; then
@@ -24827,6 +24939,237 @@ cat >>confdefs.h <<_ACEOF
 #define SIZEOF_VOID_P $ac_cv_sizeof_void_p
 _ACEOF
 
+# These typically are compiler builtins, for which AC_CHECK_FUNCS fails.
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for __builtin_bswap16" >&5
+$as_echo_n "checking for __builtin_bswap16... " >&6; }
+if ${pgac_cv__builtin_bswap16+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+call__builtin_bswap16(int x)
+{
+    return __builtin_bswap16(x);
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  pgac_cv__builtin_bswap16=yes
+else
+  pgac_cv__builtin_bswap16=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $pgac_cv__builtin_bswap16" >&5
+$as_echo "$pgac_cv__builtin_bswap16" >&6; }
+if test x"${pgac_cv__builtin_bswap16}" = xyes ; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE__BUILTIN_BSWAP16 1
+_ACEOF
+
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for __builtin_bswap32" >&5
+$as_echo_n "checking for __builtin_bswap32... " >&6; }
+if ${pgac_cv__builtin_bswap32+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+call__builtin_bswap32(int x)
+{
+    return __builtin_bswap32(x);
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  pgac_cv__builtin_bswap32=yes
+else
+  pgac_cv__builtin_bswap32=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $pgac_cv__builtin_bswap32" >&5
+$as_echo "$pgac_cv__builtin_bswap32" >&6; }
+if test x"${pgac_cv__builtin_bswap32}" = xyes ; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE__BUILTIN_BSWAP32 1
+_ACEOF
+
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for __builtin_bswap64" >&5
+$as_echo_n "checking for __builtin_bswap64... " >&6; }
+if ${pgac_cv__builtin_bswap64+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+call__builtin_bswap64(long int x)
+{
+    return __builtin_bswap64(x);
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  pgac_cv__builtin_bswap64=yes
+else
+  pgac_cv__builtin_bswap64=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $pgac_cv__builtin_bswap64" >&5
+$as_echo "$pgac_cv__builtin_bswap64" >&6; }
+if test x"${pgac_cv__builtin_bswap64}" = xyes ; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE__BUILTIN_BSWAP64 1
+_ACEOF
+
+fi
+# We assume that we needn't test all widths of these explicitly:
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for __builtin_clz" >&5
+$as_echo_n "checking for __builtin_clz... " >&6; }
+if ${pgac_cv__builtin_clz+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+call__builtin_clz(unsigned int x)
+{
+    return __builtin_clz(x);
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  pgac_cv__builtin_clz=yes
+else
+  pgac_cv__builtin_clz=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $pgac_cv__builtin_clz" >&5
+$as_echo "$pgac_cv__builtin_clz" >&6; }
+if test x"${pgac_cv__builtin_clz}" = xyes ; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE__BUILTIN_CLZ 1
+_ACEOF
+
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for __builtin_ctz" >&5
+$as_echo_n "checking for __builtin_ctz... " >&6; }
+if ${pgac_cv__builtin_ctz+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+call__builtin_ctz(unsigned int x)
+{
+    return __builtin_ctz(x);
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  pgac_cv__builtin_ctz=yes
+else
+  pgac_cv__builtin_ctz=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $pgac_cv__builtin_ctz" >&5
+$as_echo "$pgac_cv__builtin_ctz" >&6; }
+if test x"${pgac_cv__builtin_ctz}" = xyes ; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE__BUILTIN_CTZ 1
+_ACEOF
+
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for __builtin_popcount" >&5
+$as_echo_n "checking for __builtin_popcount... " >&6; }
+if ${pgac_cv__builtin_popcount+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+call__builtin_popcount(unsigned int x)
+{
+    return __builtin_popcount(x);
+}
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"; then :
+  pgac_cv__builtin_popcount=yes
+else
+  pgac_cv__builtin_popcount=no
+fi
+rm -f core conftest.err conftest.$ac_objext \
+    conftest$ac_exeext conftest.$ac_ext
+fi
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $pgac_cv__builtin_popcount" >&5
+$as_echo "$pgac_cv__builtin_popcount" >&6; }
+if test x"${pgac_cv__builtin_popcount}" = xyes ; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE__BUILTIN_POPCOUNT 1
+_ACEOF
+
+fi
+
 
 # The cast to long int works around a bug in the HP C Compiler
 # version HP92453-01 B.11.11.23709.GP, which incorrectly rejects
@@ -29832,8 +30175,8 @@ CFLAGS="-DSTREAMPLAN $CFLAGS"
 # force set char to signed char
 CFLAGS="-fsigned-char $CFLAGS"
 
-platform_version=`sh ./src/get_PlatForm_str.sh`
-is_euler=`echo $platform_version | grep euleros`
+release_file=`find /etc/ -name "euleros-release"`
+is_euler=`echo $release_file | grep EulerOS`
 # New gcc version should be compatible to old one
 if test "$CC_VERSION" = "$NEW_GCC"; then
   CFLAGS=" -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 $CFLAGS -fno-aggressive-loop-optimizations -Wno-attributes -fno-omit-frame-pointer -fno-expensive-optimizations"
